import type { AgentConfig } from "./types";

/**
 * Math Tutor Agent Configuration
 *
 * This agent is a friendly, patient math teacher for teenagers (13-19 years old).
 * It only answers questions related to mathematics and provides safe, educational content.
 */
export const mathTutorConfig: AgentConfig = {
  name: "Matematyczny Korepetytor",
  subject: "matematyka",

  // Model configuration
  // mistral-small is fast and cost-effective for most math questions
  model: "mistral-small-latest",

  // Temperature: 0.7 is a good balance between creativity and precision
  // For math, we want mostly precise answers with some flexibility in explanations
  temperature: 0.7,

  // Max tokens: 500-1000 for concise but complete answers
  maxTokens: 800,

  description: "Przyjazny korepetytor matematyki dla nastolatków, wyjaśniający trudne zagadnienia w prosty sposób.",
};

// Safety and content restrictions
export const contentRestrictions = {
  // Polish keywords to detect math-related questions
  // These words help identify if user's question is about mathematics
  mathKeywords: [
    // === LICZBY RZECZYWISTE ===
    "liczba",
    "liczby",
    "naturalna",
    "całkowita",
    "wymierna",
    "niewymierna",
    "rzeczywista",
    "zespolona",
    "potęga",
    "potęgowanie",
    "pierwiastek",
    "pierwiastkowanie",
    "logarytm",
    "logarytmowanie",
    "procent",
    "procenty",
    "promil",
    "ułamek",
    "ułamki",
    "dziesiętny",
    "zwykły",
    "wartość bezwzględna",
    "moduł",
    "przedział",
    "zbiór",
    "zbiory",
    "suma",
    "różnica",
    "iloczyn",
    "iloraz",
    "dzielnik",
    "wielokrotność",
    "NWD",
    "NWW",
    "podzielność",

    // === WYRAŻENIA ALGEBRAICZNE ===
    "wyrażenie",
    "wyrażenia algebraiczne",
    "jednomian",
    "wielomian",
    "wielomiany",
    "stopień wielomianu",
    "współczynnik",
    "wzory skróconego mnożenia",
    "kwadrat sumy",
    "kwadrat różnicy",
    "różnica kwadratów",
    "sześcian",
    "rozkład",
    "faktoryzacja",
    "wyrażenie wymierne",
    "wyrażenia wymierne",
    "działania",

    // === RÓWNANIA I NIERÓWNOŚCI ===
    "równanie",
    "równania",
    "nierówność",
    "nierówności",
    "liniowe",
    "kwadratowe",
    "wielomianowe",
    "wymierne",
    "wykładnicze",
    "logarytmiczne",
    "trygonometryczne",
    "z parametrem",
    "układ równań",
    "układ nierówności",
    "rozwiąż",
    "rozwiązanie",
    "rozwiązać",
    "oblicz",
    "obliczyć",
    "wyznacz",
    "wyznaczyć",
    "delta",
    "dyskryminant",
    "wzór",
    "wzory",
    "pierwiastki równania",
    "wartość bezwzględna",

    // === FUNKCJE ===
    "funkcja",
    "funkcje",
    "dziedzina",
    "zbiór wartości",
    "przeciwdziedzina",
    "wykres",
    "wykres funkcji",
    "monotoniczność",
    "rosnąca",
    "malejąca",
    "stała",
    "parzysta",
    "nieparzysta",
    "różnowartościowa",
    "odwrotna",
    "złożenie funkcji",
    "funkcja liniowa",
    "funkcja kwadratowa",
    "parabola",
    "wierzchołek",
    "ramiona paraboli",
    "funkcja wymierna",
    "asymptota",
    "funkcja wykładnicza",
    "funkcja logarytmiczna",
    "funkcja trygonometryczna",
    "miejsce zerowe",
    "miejsca zerowe",
    "przecięcie z osią",
    "postać ogólna",
    "postać kanoniczna",
    "postać iloczynowa",
    "współczynnik kierunkowy",
    "punkt przecięcia",

    // === TRYGONOMETRIA ===
    "trygonometria",
    "sinus",
    "cosinus",
    "tangens",
    "cotangens",
    "sin",
    "cos",
    "tg",
    "ctg",
    "kąt",
    "kąty",
    "stopień",
    "radian",
    "radiany",
    "łuk",
    "tożsamość trygonometryczna",
    "jedynka trygonometryczna",
    "twierdzenie sinusów",
    "twierdzenie cosinusów",
    "wzory redukcyjne",
    "funkcje trygonometryczne",
    "okres funkcji",

    // === PLANIMETRIA (geometria płaska) ===
    "planimetria",
    "geometria",
    "figura",
    "figury płaskie",
    "trójkąt",
    "trójkąty",
    "prostokątny",
    "równoboczny",
    "równoramienny",
    "rozwartokątny",
    "ostrokątny",
    "czworokąt",
    "kwadrat",
    "prostokąt",
    "romb",
    "równoległobok",
    "trapez",
    "deltoid",
    "wielokąt",
    "wielokąty",
    "foremny",
    "koło",
    "okrąg",
    "promień",
    "średnica",
    "cięciwa",
    "styczna",
    "sieczna",
    "łuk",
    "wycinek",
    "pole",
    "obwód",
    "przekątna",
    "wysokość",
    "podstawa",
    "bok",
    "twierdzenie Pitagorasa",
    "twierdzenie Talesa",
    "podobieństwo",
    "przystawanie",
    "skala",
    "symetria",
    "oś symetrii",
    "środek symetrii",

    // === GEOMETRIA ANALITYCZNA ===
    "geometria analityczna",
    "układ współrzędnych",
    "oś X",
    "oś Y",
    "punkt",
    "współrzędne",
    "wektor",
    "wektory",
    "długość wektora",
    "prosta",
    "proste",
    "równanie prostej",
    "kierunkowy",
    "równoległe",
    "prostopadłe",
    "odległość",
    "odległość punktu od prostej",
    "środek odcinka",
    "okrąg",
    "równanie okręgu",

    // === STEREOMETRIA (geometria przestrzenna) ===
    "stereometria",
    "bryła",
    "bryły",
    "graniastosłup",
    "ostrosłup",
    "walec",
    "stożek",
    "kula",
    "sfera",
    "prostopadłościan",
    "sześcian",
    "objętość",
    "pole powierzchni",
    "powierzchnia boczna",
    "powierzchnia całkowita",
    "krawędź",
    "wierzchołek",
    "ściana",
    "przekrój",
    "wysokość bryły",

    // === CIĄGI ===
    "ciąg",
    "ciągi",
    "arytmetyczny",
    "geometryczny",
    "różnica ciągu",
    "iloraz ciągu",
    "wyraz",
    "n-ty wyraz",
    "wzór ogólny",
    "wzór rekurencyjny",
    "suma ciągu",
    "suma szeregu",
    "szereg",
    "szeregi",
    "zbieżność",
    "rozbieżność",

    // === GRANICE I CIĄGŁOŚĆ ===
    "granica",
    "granice",
    "granica funkcji",
    "granica ciągu",
    "ciągłość",
    "ciągła",
    "nieciągłość",
    "nieskończoność",
    "dąży do",
    "lim",

    // === POCHODNE ===
    "pochodna",
    "pochodne",
    "różniczkowanie",
    "styczna do wykresu",
    "ekstremum",
    "maksimum",
    "minimum",
    "punkt przegięcia",
    "monotoniczność",
    "wypukłość",
    "wklęsłość",
    "optymalizacja",

    // === CAŁKI ===
    "całka",
    "całki",
    "całkowanie",
    "całka nieoznaczona",
    "całka oznaczona",
    "funkcja pierwotna",
    "pole pod wykresem",

    // === RACHUNEK PRAWDOPODOBIEŃSTWA I STATYSTYKA ===
    "prawdopodobieństwo",
    "statystyka",
    "zdarzenie",
    "zdarzenie losowe",
    "zdarzenie pewne",
    "zdarzenie niemożliwe",
    "przestrzeń zdarzeń",
    "średnia",
    "średnia arytmetyczna",
    "mediana",
    "dominanta",
    "moda",
    "odchylenie standardowe",
    "wariancja",
    "rozkład",
    "histogram",
    "wykres",
    "dane",
    "próba",

    // === KOMBINATORYKA ===
    "kombinatoryka",
    "permutacja",
    "wariacja",
    "kombinacja",
    "silnia",
    "symbol Newtona",
    "dwumian Newtona",
    "trójkąt Pascala",

    // === OGÓLNE SŁOWA KLUCZOWE ===
    "matematyka",
    "matma",
    "zadanie",
    "przykład",
    "dowód",
    "twierdzenie",
    "definicja",
    "własność",
    "własności",
    "rachunek",
    "obliczenia",
    "wynik",
    "odpowiedź",
    "sprawdź",
    "sprawdzić",
    "udowodnij",
    "udowodnić",
    "porównaj",
    "porównać",
    "zapisz",
    "zapisać",
    "narysuj",
    "naszkicuj",
    "wykres",
    "tabela",
    "tabelka",
  ],

  // Math symbols regex pattern
  mathSymbolsPattern: /[+\-*/=<>≤≥≠²³⁴⁵⁶⁷⁸⁹⁰√∛∜∫∑∏πθαβγδεφλμσΔ∞±×÷∈∉⊂⊃∪∩∅∀∃]|[0-9]{2,}|\^|log|ln|sin|cos|tg|ctg/,

  // Maximum message length from user (characters)
  maxMessageLength: 1000,

  // Maximum conversation history to send to API (to save costs)
  maxHistoryMessages: 15,

  // Timeout for API requests (milliseconds)
  apiTimeout: 30000, // 30 seconds

  // Age range for target audience
  targetAgeRange: {
    min: 13,
    max: 19,
  },
};

// Session limits
export const sessionLimits = {
  // Maximum session duration in minutes
  maxSessionDuration: 30,

  // Maximum number of messages per session
  maxMessagesPerSession: 50,

  // Warning threshold (percentage of limit)
  warningThreshold: 0.8, // Show warning at 80% of limit
};
